module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  modulePathIgnorePatterns: ['<rootDir>/dist/'],
  collectCoverage: true,
  collectCoverageFrom: ['src/**/*.ts', '!src/main.ts'],
  coveragePathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/dist/',
    '<rootDir>/src/main.ts',
    '<rootDir>/src/app.module.ts',
    '<rootDir>/src/config.ts',
    '\\.dto\\.ts$',
    '\\.model\\.ts$',
    '\\.repository\\.ts$',
    '\\.contract\\.ts$',
    '\\.mock\\.ts$',
    '\\.data\\.ts$',
    '\\.spec\\.ts$',
    '\\.constant\\.ts$',
    '\\.middleware\\.ts$',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['json', 'lcov', 'text', 'clover'],
  testTimeout: 10000,
  silent: true,
};
